# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
