# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_healthclub_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='healthclub_price',
            field=models.IntegerField(default=0),
        ),
    ]
