# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.CharField(default='test@gmail.com', max_length=120),
            preserve_default=False,
        ),
    ]
