# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mail',
            new_name='email',
        ),
    ]
