# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unit_cash',
            field=models.IntegerField(default=0),
        ),
    ]
