# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_profile_unit_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='is_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
