# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180508_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='attend',
            new_name='exercised',
        ),
    ]
