# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0010_auto_20180508_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_masters',
            field=models.ManyToManyField(blank=True, related_name='is_group_master', to=settings.AUTH_USER_MODEL),
        ),
    ]
