# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_groupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvite',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='profiles.Group'),
        ),
    ]
