# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthclub',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
