# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0002_auto_20180505_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthclub',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
