# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0004_remove_healthclub_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthclub',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
