# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0005_healthclub_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthclub',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
