# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0006_auto_20180506_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_healthclub',
            name='healthclub',
        ),
        migrations.RemoveField(
            model_name='user_healthclub',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Healthclub',
        ),
    ]
