# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0007_auto_20180507_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthclub',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
