# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0008_healthclub_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthclub',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
