# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0009_auto_20180508_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthclub',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
