# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0010_healthclub_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthclub',
            old_name='location',
            new_name='geometry',
        ),
    ]
