# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0011_auto_20180526_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthclub',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
