# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0015_healthclubreply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthClubReply',
            new_name='HealthClubDetailReply',
        ),
    ]
