# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0016_auto_20180526_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthclubdetailreply',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='healthclubdetailreply',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
