# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0019_auto_20180625_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthclub',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_health_master', to=settings.AUTH_USER_MODEL),
        ),
    ]
