# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180504_1551'),
        ('healthclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthclub',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthclub',
            name='master',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthclub',
            name='member',
            field=models.IntegerField(default=0),
        ),
    ]
