# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthclub', '0002_auto_20180504_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthclub',
            name='member',
        ),
    ]
